version: 2.1
orbs:
  kubernetes: circleci/kubernetes@0.11.2
  helm: circleci/helm@1.0.1
  aws-cli: circleci/aws-cli@1.3.0
  aws-ecr: circleci/aws-ecr@6.14.0
  docker: circleci/docker@1.5.0

jobs:

  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - run: |
          docker build -t madlan/sample-python:latest .
          echo $DOCKER_PASS | docker login -u gelevb --password-stdin
          docker push madlan/sample-python:latest

  push-to-ecr:
    machine: true
    environment:
      HELM_EXPERIMENTAL_OCI: 1
      COMPONENT: sample-python
    steps:
      - run: |
      - checkout
      - aws-cli/install
      - aws-cli/setup
      - helm/install-helm-client:
          version: v3.0.0
      - run: |
          export VERSION=$(cat chart/Chart.yaml | grep version: | sed -e "s/version: //")
      - run: |
          sudo chown -R $USER:$USER /etc/docker
          aws ecr get-login-password \
            --region $AWS_REGION | helm registry login \
            --username AWS \
            --password-stdin $AWS_ECR_ACCOUNT_URL
          helm chart save chart/ 654570355225.dkr.ecr.eu-west-1.amazonaws.com/helm-charts-test:$COMPONENT-$VERSION
          helm chart list
          helm chart push 654570355225.dkr.ecr.eu-west-1.amazonaws.com/helm-charts-test:$COMPONENT-$VERSION
          curl -u ${CIRCLE_API_USER_TOKEN}: -X POST --header "Content-Type: application/json" -d '{
            "parameters": {
              "component": "$COMPONENT",
              "version": "$VERSION"
            }
          }' https://circleci.com/api/v2/project/gh/madlandev/sample-umbrella/pipeline?branch=master



  deploy:
    machine: true
    environment:
      HELM_EXPERIMENTAL_OCI: 1
    steps:
      - kubernetes/install-kubectl
      - aws-cli/install
      - aws-cli/setup
      - run:
         name: Set AWS Region
         command: aws configure set region eu-west-1
      - run:
         name: Create Airflow Kubernetes Cluster kubeconfig
         command: aws eks --region eu-west-1 update-kubeconfig --name jx-cluster-staging
      - run:
         name: Set Airflow Kubernetes Cluster kubectl context
         command: kubectl config use-context arn:aws:eks:eu-west-1:654570355225:cluster/jx-cluster-staging
      - run: |
          aws sts get-caller-identity
          kubectl cluster-info --context arn:aws:eks:eu-west-1:654570355225:cluster/jx-cluster-staging
      - helm/install-helm-client:
          version: v3.0.0
      - run: |
          sudo chown -R $USER:$USER /etc/docker
          aws ecr get-login-password \
            --region $AWS_REGION | helm registry login \
            --username AWS \
            --password-stdin $AWS_ECR_ACCOUNT_URL
          helm chart pull 654570355225.dkr.ecr.eu-west-1.amazonaws.com/helm-charts-test:sample-python
          helm chart export 654570355225.dkr.ecr.eu-west-1.amazonaws.com/helm-charts-test:sample-python
          helm install sample-python ./sample-python --namespace default

workflows:
  my-little-workflow:
    jobs:
#      - build-and-push:
#          filters:
#            branches:
#              only: main
      - push-to-ecr:
          filters:
            branches:
              only: main
#      - deploy:
#          filters:
#            branches:
#              only: main
