version: 2.1
orbs:
  kubernetes: circleci/kubernetes@0.11.2
  helm: circleci/helm@1.0.1
  aws-cli: circleci/aws-cli@1.3.0
  aws-ecr: circleci/aws-ecr@6.14.0
  docker: circleci/docker@1.5.0
jobs:
  build-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: madlan/sample-python
      - docker/push:
          image: madlan/sample-python
workflows:
  version: 2
  test:
    jobs:
    - build-and-push-to-docker:
